// ─── Mock article data ────────────────────────────────────────────────────────
export const ARTICLES = [
  {
    id: 1,
    slug: "deep-clean-kitchen-guide",
    category: "kitchen",
    readTime: 5,
    date: "2024-11-12",
    image: "/kitchen_cleaing.jpg",
    featured: true,
  },
  {
    id: 2,
    slug: "bathroom-mold-prevention",
    category: "bathroom",
    readTime: 4,
    date: "2024-11-05",
    image: "/maid.jpg",
    featured: false,
  },
  {
    id: 3,
    slug: "eco-friendly-cleaning-products",
    category: "tips",
    readTime: 6,
    date: "2024-10-28",
    image: "/kitchen_cleaing.jpg",
    featured: false,
  },
  {
    id: 4,
    slug: "weekly-cleaning-schedule",
    category: "tips",
    readTime: 3,
    date: "2024-10-20",
    image: "/maid.jpg",
    featured: false,
  },
  {
    id: 5,
    slug: "carpet-stain-removal",
    category: "general",
    readTime: 5,
    date: "2024-10-14",
    image: "/kitchen_cleaing.jpg",
    featured: false,
  },
  {
    id: 6,
    slug: "spring-cleaning-checklist",
    category: "general",
    readTime: 7,
    date: "2024-10-07",
    image: "/maid.jpg",
    featured: false,
  },
];